### ISSUE TITLE
Running the server in multi-user mode

### ISSUE THREAD

**Issue by rodant** [angelo-v/docker-solid-server#4]
It would be nice to be able to start a server in multi-user mode as a step towards a more production-like setup.

I made some changes to the docker-compose-single and other related files in my fork https://github.com/rodant/docker-solid-server. I have a wildcard certificate in place and I set up my /etc/hosts accordingly as described on the NSS repository.

The server starts similarly to the single-user case, but when I try to register a new user the browser shows:

ENOENT: no such file or directory, open '/opt/solid/config/views/layouts/main.hbs'

On startup the server logs contains:
```
server_1  | Thu, 16 May 2019 16:20:41 GMT solid:authentication Error registering a new client:  { FetchError: request to https://localhost/.well-known/openid-configuration failed, reason: connect ECONNREFUSED 127.0.0.1:443
server_1  |     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/solid-server/node_modules/node-fetch/lib/index.js:1455:11)
server_1  |     at ClientRequest.emit (events.js:189:13)
server_1  |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
server_1  |     at TLSSocket.emit (events.js:189:13)
server_1  |     at emitErrorNT (internal/streams/destroy.js:82:8)
server_1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
server_1  |     at process._tickCallback (internal/process/next_tick.js:63:19)
server_1  |   message:
server_1  |    'request to https://localhost/.well-known/openid-configuration failed, reason: connect ECONNREFUSED 127.0.0.1:443',
server_1  |   type: 'system',
server_1  |   errno: 'ECONNREFUSED',
server_1  |   code: 'ECONNREFUSED' }
```
but this was also the case in single-user mode, which worked properly.

I looked at the running container and the missing openid-configuration file isn't under the expected path. Have you tried the multi-user mode or have any hint?

Best regards
Antonio.

**Comment by rodant** [comment]
What I noticed today, despite the server is configured for the port 8443, the failing request is using the standard port 443! This is strange.

server_1  | Solid server (5.0.1) running on https://localhost:8443/

**Comment by angelo-v** [comment]
The request you are talking about goes against the configured server URI, which you set to `https://localhost`. 443 is the standard HTTPS port. As you mentioned correctly this error occurs as well in single user mode, so I don't expect it to be the cause of your troubles. Besides that, you should set your public domain name within the server URI, not localhost.

Another thing is: you do not have to fork this repo in order to use solid server in multi user mode. Every option of NSS is configurable via environment variables, so you can just use my image from docker hub and set env variables that match your desires.

I actually do not see any hint, that the troubles your are having are caused from dockerizing NSS, so I guess there might be a bug in NSS itself. Did you try running it without docker? You could try asking in the [gitter chat](https://gitter.im/solid/node-solid-server) or file [an issue in the NSS repo](https://github.com/solid/node-solid-server/issues).

One thing that could go wrong with docker is volume mapping. I saw you mapped your host dir `~/tmp/solid/config` into the container. Please check if there is any content. I am not sure how docker compose handles `~`. Are files in `~/tmp/solid/config/views/layouts` anyway? Is there a `~/tmp/solid/config/views/layouts/main.hbs`?

**Comment by angelo-v** [comment]
I just tried it out myself and got it running without problems. Since I could actually not figure out how to set a flag without value, like `--multiuser` as an ENV variable, I adjusted the `command` as an alternative:

```
command: start --multiuser
```

Everything else I left unchange from the `docker-compose.simple.yml` example. I just added `127.0.0.1 solid.example username.solid.example` to my machines `/etc/hosts`.

Registration worked as expected and I could reach the POD at `https://username.solid.example`

**Comment by rodant** [comment]
Thanks Angelo for the fast reaction.
> The request you are talking about goes against the configured server URI, which you set to `https://localhost`. 443 is the standard HTTPS port. As you mentioned correctly this error occurs as well in single user mode, so I don't expect it to be the cause of your troubles. Besides that, you should set your public domain name within the server URI, not localhost.
> 
I forgot to write that I also test using the port mapping 8443::8443 to be near to the default setup, that's why I found strange the use of the default https port in the logs. 
> Another thing is: you do not have to fork this repo in order to use solid server in multi user mode. Every option of NSS is configurable via environment variables, so you can just use my image from docker hub and set env variables that match your desires.
> 
> I actually do not see any hint, that the troubles your are having are caused from dockerizing NSS, so I guess there might be a bug in NSS itself. Did you try running it without docker? You could try asking in the [gitter chat](https://gitter.im/solid/node-solid-server) or file [an issue in the NSS repo](https://github.com/solid/node-solid-server/issues).
> 
I tested today without docker, just installing the server and got the same problem. I wrote an issue: https://github.com/solid/node-solid-server/issues/1189.
> One thing that could go wrong with docker is volume mapping. I saw you mapped your host dir `~/tmp/solid/config` into the container. Please check if there is any content. I am not sure how docker compose handles `~`. Are files in `~/tmp/solid/config/views/layouts` anyway? Is there a `~/tmp/solid/config/views/layouts/main.hbs`?
The mapping isn't the problem, the server wrote files there, I checked it.

**Comment by rodant** [comment]
> I just tried it out myself and got it running without problems. Since I could actually not figure out how to set a flag without value, like `--multiuser` as an ENV variable, I adjusted the `command` as an alternative:
> 
> ```
> command: start --multiuser
> ```
> 
> Everything else I left unchange from the `docker-compose.simple.yml` example. I just added `127.0.0.1 solid.example username.solid.example` to my machines `/etc/hosts`.
> 
> Registration worked as expected and I could reach the POD at `https://username.solid.example`

I'll try to proceed like you and see if still have issues. Thanks again.

**Comment by rodant** [comment]
It worked now, the point of not using localhost as the server URI was important and neither in the browser address bar, which is somehow unusual for me.

Thanks again for your help.
